### ISSUE TITLE
AVERTISSEMENT: RaidBossSpawnManager: Error while initializing RaidBossSpawnManager: null

### ISSUE THREAD

**Issue by Piikmin** [L2J/L2J_DataPack#238]
Hello,

An error when we launch the gameserver on the last version.

```
nov. 11, 2015 11:36:37 PM com.l2jserver.gameserver.instancemanager.RaidBossSpawnManager load
AVERTISSEMENT: RaidBossSpawnManager: Error while initializing RaidBossSpawnManager: null
java.lang.NullPointerException
	at com.l2jserver.gameserver.model.L2Spawn.getId(L2Spawn.java:346)
	at com.l2jserver.gameserver.instancemanager.RaidBossSpawnManager.addNewSpawn(RaidBossSpawnManager.java:220)
	at com.l2jserver.gameserver.instancemanager.RaidBossSpawnManager.load(RaidBossSpawnManager.java:94)
	at com.l2jserver.gameserver.instancemanager.RaidBossSpawnManager.<init>(RaidBossSpawnManager.java:67)
	at com.l2jserver.gameserver.instancemanager.RaidBossSpawnManager$SingletonHolder.<clinit>(RaidBossSpawnManager.java:563)
	at com.l2jserver.gameserver.instancemanager.RaidBossSpawnManager.getInstance(RaidBossSpawnManager.java:558)
	at hellbound.AI.Typhoon.<init>(Typhoon.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at hellbound.HellboundLoader.main(HellboundLoader.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.l2jserver.script.java.JavaScriptEngine.evalClass(JavaScriptEngine.java:464)
	at com.l2jserver.script.java.JavaScriptEngine$JavaCompiledScript.eval(JavaScriptEngine.java:96)
	at com.l2jserver.gameserver.scripting.L2ScriptEngineManager.executeScript(L2ScriptEngineManager.java:377)
	at com.l2jserver.gameserver.scripting.L2ScriptEngineManager.executeScript(L2ScriptEngineManager.java:326)
	at com.l2jserver.gameserver.scripting.L2ScriptEngineManager.executeScriptList(L2ScriptEngineManager.java:226)
	at com.l2jserver.gameserver.GameServer.<init>(GameServer.java:308)
	at com.l2jserver.gameserver.GameServer.main(GameServer.java:514)```

Thx.

**Comment by Sacrifice78** [comment]
For me ... works well.

**Comment by Zealar** [comment]
There is something bad in your setup so is not load data properly missing or bad files.
