### ISSUE TITLE
AVERTISSEMENT: CastleManorManager: Unable to load manor data!

### ISSUE THREAD

**Issue by Piikmin** [L2J/L2J_DataPack#239]
Hello,

An error when we launch the gameserver on the last version. Just for info.

```
nov. 11, 2015 11:37:00 PM com.l2jserver.gameserver.instancemanager.CastleManorManager loadDb
AVERTISSEMENT: CastleManorManager: Unable to load manor data!
java.sql.SQLException: Column 'amount' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:959)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1076)
	at com.mysql.jdbc.ResultSetImpl.getLong(ResultSetImpl.java:2757)
	at com.zaxxer.hikari.proxy.HikariResultSetProxy.getLong(HikariResultSetProxy.java)
	at com.l2jserver.gameserver.instancemanager.CastleManorManager.loadDb(CastleManorManager.java:192)
	at com.l2jserver.gameserver.instancemanager.CastleManorManager.<init>(CastleManorManager.java:84)
	at com.l2jserver.gameserver.instancemanager.CastleManorManager$SingletonHolder.<clinit>(CastleManorManager.java:819)
	at com.l2jserver.gameserver.instancemanager.CastleManorManager.getInstance(CastleManorManager.java:814)
	at com.l2jserver.gameserver.GameServer.<init>(GameServer.java:332)
	at com.l2jserver.gameserver.GameServer.main(GameServer.java:514)
```

Thx.

**Comment by Sacrifice78** [comment]
For me works well
