### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by Sacrifice78** [L2J/L2J_DataPack#249]
\game\data\scripts\quests\QuestMasterHandler.java
java.lang.NullPointerException
	at quests.Q00336_CoinsOfMagic.Q00336_CoinsOfMagic.getRandomPlayerFromParty(Q00336_CoinsOfMagic.java:1795)
	at quests.Q00336_CoinsOfMagic.Q00336_CoinsOfMagic.onKill(Q00336_CoinsOfMagic.java:1114)
	at com.l2jserver.gameserver.model.quest.Quest.notifyKill(Quest.java:589)
	at com.l2jserver.gameserver.model.quest.Quest.lambda$addKillId$54(Quest.java:1930)
	at com.l2jserver.gameserver.model.events.listeners.ConsumerEventListener.executeEvent(ConsumerEventListener.java:46)
	at com.l2jserver.gameserver.model.events.EventDispatcher.notifyToListeners(EventDispatcher.java:242)
	at com.l2jserver.gameserver.model.events.EventDispatcher.notifyEventImpl(EventDispatcher.java:216)
	at com.l2jserver.gameserver.model.events.EventDispatcher.notifyEvent(EventDispatcher.java:85)
	at com.l2jserver.gameserver.model.events.EventDispatcher.lambda$notifyEventAsyncDelayed$231(EventDispatcher.java:135)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sacrifice78** [comment]
@Zealar Great man!!! +1
