### ISSUE TITLE
Got problem on Items Load !

### ISSUE THREAD

**Issue by Arverion** [L2J/L2J_DataPack#261]
java.util.NoSuchElementException: Unknown name 'rCrit' for enum BaseStats
        at com.l2jserver.gameserver.model.stats.Stats.valueOfXml(Stats.java:224)

        at com.l2jserver.gameserver.engines.DocumentBase.attachFunc(DocumentBase
.java:253)
        at com.l2jserver.gameserver.engines.DocumentBase.parseTemplate(DocumentB
ase.java:245)
        at com.l2jserver.gameserver.engines.DocumentBase.parseTemplate(DocumentB
ase.java:190)
        at com.l2jserver.gameserver.engines.items.DocumentItem.parseItem(Documen
tItem.java:134)
        at com.l2jserver.gameserver.engines.items.DocumentItem.parseDocument(Doc
umentItem.java:85)
        at com.l2jserver.gameserver.engines.DocumentBase.parse(DocumentBase.java
:161)
        at com.l2jserver.gameserver.engines.DocumentEngine.loadItems(DocumentEng
ine.java:124)
        at com.l2jserver.gameserver.datatables.ItemTable.load(ItemTable.java:128
)
        at com.l2jserver.gameserver.datatables.ItemTable.<init>(ItemTable.java:1
19)
        at com.l2jserver.gameserver.datatables.ItemTable$SingletonHolder.<clinit
>(ItemTable.java:418)
        at com.l2jserver.gameserver.datatables.ItemTable.getInstance(ItemTable.j
ava:114)
        at com.l2jserver.gameserver.GameServer.<init>(GameServer.java:203)
        at com.l2jserver.gameserver.GameServer.main(GameServer.java:453)

[05/12 05:46:52] Cannot create item 6594
java.util.NoSuchElementException: Unknown name 'rCrit' for enum BaseStats
        at com.l2jserver.gameserver.model.stats.Stats.valueOfXml(Stats.java:224)

        at com.l2jserver.gameserver.engines.DocumentBase.attachFunc(DocumentBase
.java:253)
        at com.l2jserver.gameserver.engines.DocumentBase.parseTemplate(DocumentB
ase.java:245)
        at com.l2jserver.gameserver.engines.DocumentBase.parseTemplate(DocumentB
ase.java:190)
        at com.l2jserver.gameserver.engines.items.DocumentItem.parseItem(Documen
tItem.java:134)
        at com.l2jserver.gameserver.engines.items.DocumentItem.parseDocument(Doc
umentItem.java:85)
        at com.l2jserver.gameserver.engines.DocumentBase.parse(DocumentBase.java
:161)
        at com.l2jserver.gameserver.engines.DocumentEngine.loadItems(DocumentEng
ine.java:124)
        at com.l2jserver.gameserver.datatables.ItemTable.load(ItemTable.java:128
)
        at com.l2jserver.gameserver.datatables.ItemTable.<init>(ItemTable.java:1
19)
        at com.l2jserver.gameserver.datatables.ItemTable$SingletonHolder.<clinit
>(ItemTable.java:418)
        at com.l2jserver.gameserver.datatables.ItemTable.getInstance(ItemTable.j
ava:114)
        at com.l2jserver.gameserver.GameServer.<init>(GameServer.java:203)
        at com.l2jserver.gameserver.GameServer.main(GameServer.java:453)

[05/12 05:46:52] Cannot create item 6595
java.util.NoSuchElementException: Unknown name 'rCrit' for enum BaseStats
        at com.l2jserver.gameserver.model.stats.Stats.valueOfXml(Stats.java:224)

        at com.l2jserver.gameserver.engines.DocumentBase.attachFunc(DocumentBase
.java:253)
        at com.l2jserver.gameserver.engines.DocumentBase.parseTemplate(DocumentB
ase.java:245)
        at com.l2jserver.gameserver.engines.DocumentBase.parseTemplate(DocumentB
ase.java:190)
        at com.l2jserver.gameserver.engines.items.DocumentItem.parseItem(Documen
tItem.java:134)
        at com.l2jserver.gameserver.engines.items.DocumentItem.parseDocument(Doc
umentItem.java:85)
        at com.l2jserver.gameserver.engines.DocumentBase.parse(DocumentBase.java
:161)
        at com.l2jserver.gameserver.engines.DocumentEngine.loadItems(DocumentEng
ine.java:124)
        at com.l2jserver.gameserver.datatables.ItemTable.load(ItemTable.java:128
)
        at com.l2jserver.gameserver.datatables.ItemTable.<init>(ItemTable.java:1
19)
        at com.l2jserver.gameserver.datatables.ItemTable$SingletonHolder.<clinit
>(ItemTable.java:418)
        at com.l2jserver.gameserver.datatables.ItemTable.getInstance(ItemTable.j
ava:114)
        at com.l2jserver.gameserver.GameServer.<init>(GameServer.java:203)
        at com.l2jserver.gameserver.GameServer.main(GameServer.java:453)

i get this error on loading Items , Help please !

Last Develop version !

**Comment by Zealar** [comment]
Update your files "rCrit" is replaced by "critRate"
