### ISSUE TITLE
Exception in L2Skill.getTargetList(): null java.lang.NullPointerException

### ISSUE THREAD

**Issue by ghost** [L2J/L2J_DataPack#295]
ene 12, 2016 5:12:22 PM com.l2jserver.gameserver.model.skills.Skill getTargetList
ADVERTENCIA: Exception in L2Skill.getTargetList(): null
java.lang.NullPointerException
	at handlers.targethandlers.EnemySummon.getTargetList(EnemySummon.java:37)
	at com.l2jserver.gameserver.model.skills.Skill.getTargetList(Skill.java:1105)
	at com.l2jserver.gameserver.model.skills.Skill.getTargetList(Skill.java:1074)
	at com.l2jserver.gameserver.model.skills.Skill.getFirstOfTargetList(Skill.java:1123)
	at com.l2jserver.gameserver.model.actor.instance.L2PcInstance.useMagic(L2PcInstance.java:8455)
	at com.l2jserver.gameserver.network.clientpackets.RequestMagicSkillUse.runImpl(RequestMagicSkillUse.java:119)
	at com.l2jserver.gameserver.network.clientpackets.L2GameClientPacket.run(L2GameClientPacket.java:69)
	at com.l2jserver.gameserver.network.L2GameClient.run(L2GameClient.java:1134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Sacrifice78** [comment]
This issue is for core. Sorry my error.

**Comment by mhoska** [comment]
just check add a check like != null

**Comment by Sacrifice78** [comment]
public L2Object[] getTargetList(L2Character activeChar, boolean onlyFirst)	{		// Init to null the target of the skill		L2Character target = null;				// Get the L2Objcet targeted by the user of the skill at this moment		L2Object objTarget = activeChar.getTarget();		// If the L2Object targeted is a L2Character, it becomes the L2Character target		if (objTarget instanceof L2Character && objTarget != null)		{			target = (L2Character) objTarget;		}				return getTargetList(activeChar, onlyFirst, target);	}
